// Card Collection Club — Auto-generated price data
// Last updated: 2026-02-17T23:00:23.965751+11:00
// Exchange rate USD→AUD: 1.41
// Source: PriceCharting + eBay AU sold listings
// DO NOT EDIT — regenerated by update-website.py

var CARD_DB = [
  {
    "name": "Charizard ex",
    "set": "Obsidian Flames",
    "num": "228/197",
    "tcg": "Pokemon",
    "rarity": "SAR",
    "lang": "EN",
    "img": "https://images.pokemontcg.io/sv3/228_hires.png",
    "raw": 38.89,
    "psa9": 63.45,
    "psa10": 282.0,
    "trend": "up"
  },
  {
    "name": "Umbreon VMAX",
    "set": "Evolving Skies",
    "num": "215/203",
    "tcg": "Pokemon",
    "rarity": "Alt Art Secret",
    "lang": "EN",
    "img": "https://images.pokemontcg.io/swsh7/215_hires.png",
    "raw": 2609.63,
    "psa9": 2705.45,
    "psa10": 5006.2,
    "trend": "flat"
  },
  {
    "name": "Pikachu VMAX",
    "set": "Vivid Voltage",
    "num": "188/185",
    "tcg": "Pokemon",
    "rarity": "Rainbow Rare",
    "lang": "EN",
    "img": "https://images.pokemontcg.io/swsh4/188_hires.png",
    "raw": 277.98,
    "psa9": 211.5,
    "psa10": 431.71,
    "trend": "flat"
  },
  {
    "name": "Shanks",
    "set": "Romance Dawn",
    "num": "OP01-120",
    "tcg": "One Piece",
    "rarity": "SEC",
    "lang": "EN",
    "img": "https://images.pokemontcg.io/sv3/228_hires.png",
    "raw": 551.49,
    "psa9": 42.3,
    "psa10": 141.0,
    "trend": "up"
  },
  {
    "name": "Nami",
    "set": "Romance Dawn",
    "num": "OP01-016",
    "tcg": "One Piece",
    "rarity": "SEC",
    "lang": "EN",
    "img": "https://images.pokemontcg.io/sv3/228_hires.png",
    "raw": 105.04,
    "psa9": 514.65,
    "psa10": 1043.68,
    "trend": "up"
  }
];
