[build]
  publish = "."

[[redirects]]
  from = "https://www.cardcollectionclub.com/*"
  to = "https://cardcollectionclub.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
